/* Generated by re2c 1.0.1 on Wed Jan 26 13:44:47 2022 */
// lex.re
#include "../localTypes.h"
#include "../gram.h"
                                   // end of re2c block

#define COMMENT_TOKEN -2

/*e*/
u8* lex(u8 *sourceCode, TokenInfo *t)/*p;*/
{
	u8 *YYCURSOR = sourceCode;
	u8 *YYMARKER;
	u8 *start;


	loop:
	start = YYCURSOR;

	
{
	u8 yych;
	unsigned int yyaccept = 0;
	yych = *YYCURSOR;
	if (yych <= ' ') {
		if (yych <= '\n') {
			if (yych <= 0x00) goto yy2;
			if (yych <= 0x08) goto yy4;
			if (yych <= '\t') goto yy6;
			goto yy8;
		} else {
			if (yych == '\r') goto yy6;
			if (yych <= 0x1F) goto yy4;
			goto yy6;
		}
	} else {
		if (yych <= '/') {
			if (yych == '"') goto yy10;
			if (yych <= '.') goto yy4;
			goto yy11;
		} else {
			if (yych <= '9') {
				if (yych <= '0') goto yy12;
				goto yy14;
			} else {
				if (yych == ';') goto yy16;
				goto yy4;
			}
		}
	}
yy2:
	++YYCURSOR;
	{
		t->tokenType = 0;
		return YYCURSOR - 1;
	}
yy4:
	++YYCURSOR;
yy5:
	{
		t->tokenType = 0;
		io_printi(t->lineNumber);
		io_prints(" :lexical error\n");
		return 0;
	}
yy6:
	++YYCURSOR;
	{ goto loop; }
yy8:
	++YYCURSOR;
	{
		t->lineNumber++;
		goto loop;
	}
yy10:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych <= 0x00) goto yy5;
	goto yy19;
yy11:
	yych = *++YYCURSOR;
	if (yych == '/') goto yy25;
	goto yy5;
yy12:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych == 'x') goto yy28;
	goto yy15;
yy13:
	{
		t->tokenType = INTEGER;
		t->length    = s2i(start);
		return YYCURSOR;
	}
yy14:
	yych = *++YYCURSOR;
yy15:
	if (yych <= '/') goto yy13;
	if (yych <= '9') goto yy14;
	goto yy13;
yy16:
	++YYCURSOR;
	{
		t->tokenType = SEMI;
		return YYCURSOR;
	}
yy18:
	yych = *++YYCURSOR;
yy19:
	if (yych <= '"') {
		if (yych <= 0x00) goto yy20;
		if (yych <= '!') goto yy18;
		goto yy21;
	} else {
		if (yych == '\\') goto yy23;
		goto yy18;
	}
yy20:
	YYCURSOR = YYMARKER;
	if (yyaccept <= 1) {
		if (yyaccept == 0) {
			goto yy5;
		} else {
			goto yy13;
		}
	} else {
		goto yy22;
	}
yy21:
	++YYCURSOR;
yy22:
	{
		t->tokenType = STRING_LIT;
		start++;
		t->string = start;
		t->length = YYCURSOR - start - 1;
		return YYCURSOR;
	}
yy23:
	yych = *++YYCURSOR;
	if (yych <= '"') {
		if (yych <= 0x00) goto yy20;
		if (yych <= '!') goto yy18;
		goto yy29;
	} else {
		if (yych == '\\') goto yy23;
		goto yy18;
	}
yy25:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy27;
	if (yych != '\n') goto yy25;
yy27:
	{
		t->tokenType = COMMENT_TOKEN;
		t->string = start;
		t->length = YYCURSOR - start;
		return YYCURSOR;
	}
yy28:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy20;
	if (yych <= '9') goto yy30;
	if (yych <= '@') goto yy20;
	if (yych <= 'F') goto yy30;
	goto yy20;
yy29:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych <= '"') {
		if (yych <= 0x00) goto yy22;
		if (yych <= '!') goto yy18;
		goto yy21;
	} else {
		if (yych == '\\') goto yy23;
		goto yy18;
	}
yy30:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy13;
	if (yych <= '9') goto yy30;
	if (yych <= '@') goto yy13;
	if (yych <= 'F') goto yy30;
	goto yy13;
}
                                  // end of re2c block
}
